# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'palmly-app' do
  use_frameworks!

  # Pods for ImageClassification
   pod 'TensorFlowLiteSwift'
end